### PR TITLE
Add eSOP-12B footprint ("K" package)

### PR DESCRIPTION
**Pull request by evanshultz**
New package from Power Int. See page 23 of https://ac-dc.power.com/sites/default/files/product-docs/tinyswitch-4_family_datasheet.pdf.

There is one KLC violation of section 3.1 due to the pin 1 marking. I emulated the pin 1 marking style shown in the datasheet using a 0.45mm silk line. If this is unacceptable, please suggest a preferred way or I'll come up with another solution (maybe an angled 0.12mm line across the pin 1 corner inside the silk rectangle).

Footprint image:
image

FYI, this goes with my PR for the schematic symbols at https://github.com/KiCad/kicad-library/pull/845.

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

nice work. Please still change the following items:
1. proposal: add 1EP (or so) so the filename/footprint name (we have that e.g. for the SOIC-8
2. please add F.Fab layer
3. please reposition labels as e.g. here:
2016-12-21 08_11_37-bibliotheksbrowser housings_soic https___github com_kicad_housings_soic pret

Best,
JAN

**Comment by evanshultz** [comment]
Thank you!

1. I didn't do that because this is a Power Integrations-specific footprint in their unique lib. The package name "eSOP-12B" already indicates a thermal pad. I'm not saying "no", just explaining why I did what I did so that we can determine the right process for KiCad.
2. Just checking, but looking at the above example shouldn't the fab layer be square if it's the package outline? It's unclear to me why, for this package, fab and silk should be different. I can't put any component under the package, so the silk should always be present and will give a good outline to manufacturing/QA folks seeing the actual board. And if I need a fab drawing, the rectangle will serve the same purpose. I added a fab rectangle on top of the silk; is there a reason for the rectangles to be different in this case?
3. Done

**Comment by jkriege2** [comment]
ad 1) OK ... you're right ;-)

ad 2) yes it should be ... + it should have the pin1-mark ... so I think that is fine (I would have gone for a circle for pin1-mark on F.Fab ... but that's my taste I think ;-) The idea of the Silf/Fab is this: F.FAB shows the packages, as they will be soldered, but is NOT printed onto the PCB. the silkscreen is printed onto the PCB (with limited resolution, thus the requirements for grid and witdth) and will guide assembly. It will also have a certain height (a few 1/10mm I think). So especially for SMD parts the SilkSCreen should not be below the packages, so they are not lifted by the silk, which may cause problems when soldering (especially a problem for small packages)

**Comment by jkriege2** [comment]
So could you move the silkscreen from under the package.

Thanks,
JAN

**Comment by evanshultz** [comment]
Hi Jan,

I've never seen silk under parts be a problem. I've many boards this way and and seen loads of boards designed this way. Silk under parts is common. I also spoke with a few experienced librarians and process engineers who I trust and they've never seen issues due to silk under parts.

So while I disagree with avoiding silk under parts, if I want this PR to be accepted I have to play by KiCad's rules (unless the rules change). I also prefer a filled dot to indicate pin 1, but many KiCad footprints use an extended silk line. I tried to replicate that style on this footprint with the above patch. Please take a look

**Comment by jkriege2** [comment]
What about these two small changes:
2016-12-23 12_48_02-footprinteditor keine aktive bibliothek

Would that be OK for you?

Best,
JAN

PS: Personally I don't care so much about the style, but I try to stick to the style set for the KiCAD lib ... 
PPS: I think the problem with silk under part is mainly for very small SMD-parts that are near to the surface (SO-XX usually have at least the copper-height between plastic bottom and PCB) ...

**Comment by evanshultz** [comment]
Hi Jan,

Can you help me understand the reason? If silk should represent the physical part, why offset it? Certainly the fab drawing should be the actual part size, so I'm unclear why those objects wouldn't be on top of each other (where the silk doesn't go over exposed copper, anyway).

And with regards to removing the horizontal silk lines, why not leave them in place as they don't cross the pads? The actual part has a bump on the bottom so the silk won't interfere with the part body. I see just two lines and a full rectangle mixed throughout the library so no clear standard is obvious to me.

And one question from me: I used pin 13 for the EP. The part doesn't actually have 13 pins, so I felt that was a bit weird. Is there a standard KiCad nomenclature for pad names in this case (footprint name is "-EP" is in KLC but nothing about pad names)?

**Comment by jkriege2** [comment]
Hi!

About the EP, it's usually NumberOfPins+1, so pin 13 is fine!

About the silk, I think that's the same we discuss here https://github.com/KiCad/TO_SOT_Packages_SMD.pretty/pull/29 (and IPC, as you noted there). Maybe we wait until we get more optinions there and then make everything looking the same! On the other hand, I think at least the SOIC-footprints are well accepted everywhere, so also this one should orient on the SOIC-style?
2016-12-25 15_15_22-bibliotheksbrowser housings_soic https___github com_kicad_housings_soic pret

Does that help?
JAN

**Comment by evanshultz** [comment]
Agreed that we can stick to this as a standard for SOIC. However, one question about this notch/chamfer: is there a typical value that it should consume on a particular edge of the fab rectangle? For example, 20% or 25% of the short side should be a notch/chamfer?

My intent isn't to be pedantic or annoying, but improving the standard will allow library updates to happen and new contributors to more easily know what to do. I would like to participate in improving KiCad's libraries and I hopefully you all agree that it's worthwhile to discuss and nail down these questions. :)

**Comment by jkriege2** [comment]
@SchrodingersGat do you know whether there is a standard for the bevel size? maybe 1mm?

**Comment by SchrodingersGat** [comment]
1mm is standard, reduced size if the side length is < 2mm I believe

**Comment by evanshultz** [comment]
1mm chamfer added to fab. Anything else before merge?

**Comment by jkriege2** [comment]
Hi!

please move the VERTICAL Silkscreen lines by ~0.06-0.12mm to the left/right, so it is outside the actual package. Otherwise: looks fine to me (KLC 6.5)!

Best,
JAN

**Comment by evanshultz** [comment]
Hi Jan,

OK, I think this is good now. The vertical lines are now fully clear and I removed to horizontal lines. I didn't fully grasp this clause before but now I understand the offset between fab and silk that KLC calls for.

And please let me mention here how much I appreciate all your support recently. As a new contributor, there is a lot to learn and you have been so polite and helpful!

**Comment by jkriege2** [comment]
yes, looks good now ... and many thanks for the contrib and the work you put in ,-)

JAN

**Pull request merged**
